# Generated by Django 4.2.4 on 2024-05-29 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50, unique=True)),
                ("pic", models.ImageField(upload_to="uploads/brand")),
            ],
        ),
        migrations.CreateModel(
            name="Buyer",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=30)),
                ("username", models.CharField(max_length=30, unique=True)),
                ("email", models.EmailField(max_length=30)),
                ("phone", models.CharField(max_length=15)),
                ("address", models.TextField(blank=True, default="", null=True)),
                ("pin", models.IntegerField(blank=True, default="", null=True)),
                (
                    "city",
                    models.CharField(blank=True, default="", max_length=30, null=True),
                ),
                (
                    "state",
                    models.CharField(blank=True, default="", max_length=30, null=True),
                ),
                (
                    "pic",
                    models.ImageField(
                        blank=True, default="", null=True, upload_to="uploads/users"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Maincategory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Subcategory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=30)),
                ("baseprice", models.IntegerField()),
                ("discount", models.IntegerField()),
                ("finalprice", models.IntegerField()),
                ("stock", models.BooleanField(default=True)),
                ("color", models.CharField(max_length=30)),
                ("size", models.CharField(max_length=20)),
                ("description", models.TextField(default="")),
                ("pic1", models.ImageField(upload_to="uploads/product")),
                (
                    "pic2",
                    models.ImageField(
                        blank=True, default=None, null=True, upload_to="uploads/product"
                    ),
                ),
                (
                    "pic3",
                    models.ImageField(
                        blank=True, default=None, null=True, upload_to="uploads/product"
                    ),
                ),
                (
                    "pic4",
                    models.ImageField(
                        blank=True, default=None, null=True, upload_to="uploads/product"
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.brand"
                    ),
                ),
                (
                    "maincategory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.maincategory",
                    ),
                ),
                (
                    "subcategory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.subcategory",
                    ),
                ),
            ],
        ),
    ]
