# Generated by Django 4.2.4 on 2024-05-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buyer",
            name="pin",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
