# Generated by Django 4.2.4 on 2024-05-29 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_alter_buyer_pin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buyer",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
