# Generated by Django 4.2.4 on 2024-05-29 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0003_alter_buyer_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buyer",
            name="phone",
            field=models.CharField(default="", max_length=15),
        ),
    ]
