# Generated by Django 4.2.4 on 2024-06-27 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0006_checkout_checkoutproduct"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=50)),
                ("phone", models.CharField(max_length=15)),
                ("subject", models.TextField()),
                ("message", models.TextField()),
                ("status", models.BooleanField(default=True)),
                ("date", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Newslatter",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("message", models.TextField()),
                ("pic", models.ImageField(upload_to="uploads/testimonials")),
            ],
        ),
    ]
