# Generated by Django 4.2.4 on 2024-07-01 04:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0007_contact_newslatter_testimonial"),
    ]

    operations = [
        migrations.AddField(
            model_name="buyer",
            name="otp",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
